name: flutter_analyze_and_test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    name: sample test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --verbose --coverage --coverage-path=~/coverage/lcov.info
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info
